files:
  - source: /forge/src/main/resources/assets/create_factory_logistics/lang/en_us.json
    translation: /forge/src/main/resources/assets/create_factory_logistics/lang/%locale_with_underscore%.json
