pluginManagement {
    repositories {
        maven { url = 'https://maven.zznty.ru/releases' }
        gradlePluginPortal()
        mavenCentral()
    }
}

include ':abstractions'
include ':forge'

project(':abstractions').name = "create_factory_abstractions-${minecraft_version}"
project(':forge').name = "${mod_id}-${minecraft_version}"
